### ISSUE TITLE
Driver [pushbullet] not supported.

### ISSUE THREAD

**Issue by Kryptonit3** [SocialiteProviders/Pushbullet#2]
I am getting the following after following documentation

~~~
exception 'InvalidArgumentException' with message 'Driver [pushbullet] not supported.' 
in /home/kryptonit3/gandc/storage/framework/compiled.php:11270
Stack trace:
#0 /home/kryptonit3/gandc/storage/framework/compiled.php(11258): Illuminate\Support\Manager->createDriver('pushbullet')
#1 /home/kryptonit3/gandc/vendor/laravel/socialite/src/SocialiteManager.php(26): Illuminate\Support\Manager->driver('pushbullet')
#2 /home/kryptonit3/gandc/storage/framework/compiled.php(5301): Laravel\Socialite\SocialiteManager->with('pushbullet')
#3 /home/kryptonit3/gandc/app/Http/routes.php(115): Illuminate\Support\Facades\Facade::__callStatic('with', Array)
#4 /home/kryptonit3/gandc/app/Http/routes.php(115): Laravel\Socialite\Facades\Socialite::with('pushbullet')
#5 [internal function]: gandc\Providers\RouteServiceProvider->{closure}()
#6 /home/kryptonit3/gandc/storage/framework/compiled.php(7298): call_user_func_array(Object(Closure), Array)
#7 /home/kryptonit3/gandc/storage/framework/compiled.php(7285): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#8 /home/kryptonit3/gandc/storage/framework/compiled.php(6954): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /home/kryptonit3/gandc/storage/framework/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/kryptonit3/gandc/storage/framework/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /home/kryptonit3/gandc/storage/framework/compiled.php(6955): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/kryptonit3/gandc/storage/framework/compiled.php(6944): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 /home/kryptonit3/gandc/storage/framework/compiled.php(6929): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /home/kryptonit3/gandc/storage/framework/compiled.php(1935): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#18 /home/kryptonit3/gandc/storage/framework/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/kryptonit3/gandc/storage/framework/compiled.php(2438): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/kryptonit3/gandc/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): gandc\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/kryptonit3/gandc/storage/framework/compiled.php(12083): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /home/kryptonit3/gandc/storage/framework/compiled.php(10785): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/kryptonit3/gandc/storage/framework/compiled.php(11789): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/kryptonit3/gandc/storage/framework/compiled.php(11738): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/kryptonit3/gandc/storage/framework/compiled.php(2478): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/kryptonit3/gandc/storage/framework/compiled.php(8944): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/kryptonit3/gandc/storage/framework/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /home/kryptonit3/gandc/storage/framework/compiled.php(1891): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /home/kryptonit3/gandc/storage/framework/compiled.php(1880): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#36 /home/kryptonit3/gandc/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#37 {main}
~~~

**Comment by DraperStudio** [comment]
Tested it locally and no problem whatsoever installing and using the provider.

Have you registered the PushbulletExtendSocialite inside of the EventServiceProvider like mentioned here? http://socialiteproviders.github.io/providers/pushbullet/

**Comment by Kryptonit3** [comment]
Here are my configs

app.php
~~~
	'providers' => [
		'SocialiteProviders\Manager\ServiceProvider',
	],

	'aliases' => [
		'Socialite'   => 'Laravel\Socialite\Facades\Socialite',
	],
~~~

routes.php
~~~
Route::get('test', function() {

    return Socialite::with('pushbullet')->redirect();

});
~~~

EventServiceProvider.php
~~~
	protected $listen = [
		'event.name' => [
			'EventListener',
			'SocialiteProviders\Manager\SocialiteWasCalled' => [
				'SocialiteProviders\Pushbullet\PushbulletExtendSocialite@handle',
			],
		],
	];
~~~

services.php
~~~
return [

	'pushbullet' => [
		'client_id' => env('PUSHBULLET_KEY'),
		'client_secret' => env('PUSHBULLET_SECRET'),
		'redirect' => env('PUSHBULLET_REDIRECT_URI'),
	],

];
~~~

.env
~~~
PUSHBULLET_KEY=mypublickeyblah
PUSHBULLET_SECRET=mysecretkeyblah
PUSHBULLET_REDIRECT_URI=https://mysite.co
~~~

composer.json
~~~
"require": {
	"laravel/framework": "5.0.*",
	"laravel/socialite": "~2.0",
	"socialiteproviders/pushbullet": "~1.0"
},
~~~

These are the only files I have modified. When I go to https://mysite.co/test I get that error.

**Comment by DraperStudio** [comment]
I don't know if it is a typo or not, but if so you should change this.

```php
protected $listen = [
    'event.name' => [
        'EventListener',
        'SocialiteProviders\Manager\SocialiteWasCalled' => [
            'SocialiteProviders\Pushbullet\PushbulletExtendSocialite@handle',
        ],
    ],
];
```

to this.

```php
protected $listen = [
    'event.name' => [
        'EventListener',
    ],

    'SocialiteProviders\Manager\SocialiteWasCalled' => [
            'SocialiteProviders\Pushbullet\PushbulletExtendSocialite@handle',
        ],
    ],
];
```

**Comment by Kryptonit3** [comment]
That was it. Thanks!
